### ISSUE TITLE
How to let the rubydung remake build run on computer?

### ISSUE THREAD

**Issue by WinPad1993** [nasko222/old-mc-mods#1]
I downloaded it,but I cannot find any way to paly it,What can I do?Thanks.

**Comment by nasko222** [comment]
Use a launcher like Betacraft, copy the info file of any preclassic to match the name of the jar, the jar has to be in versions and the info file has to be in versions/jsons

**Comment by WinPad1993** [comment]
Thanks very much,now the game runnin.But there is a bug(like this picture),the trees are under the grass!And,there are too many tree towers under ground.But there are not any trees on the ground.This is different from some of videos about this remake.How to fix it?Thanks
![image](https://github.com/nasko222/old-mc-mods/assets/109840619/f4f5bdc4-504e-45c4-a025-2bff7a90d835)
PS:I used all of pre-c versions.But not any changes.

**Comment by nasko222** [comment]
It could be graphics card related issue, also these mods in this repo are old and out of support, so i am not looking forward to fix it (nor i know how)

**Comment by WinPad1993** [comment]
That‘s OK.
